environment:
    gitconfig: "ENCRYPTED[!ba2ea5afd7d8a0c02f9064d2361f9f8f8a9a1a40eeb7d3afb4df86d62a19d2d2c92225eaff2f97370cee55bf3b020304!]"
    credentials: "ENCRYPTED[!3ccd03b7576c7ca3cf8e0104019fe3013fadbe70ef25d79611996000325dbee9da40f28880d4baf6be8120d8bb90afbb!]"
    rcloneconfig: "ENCRYPTED[!230925cbcd20163b32d1d28045b6038db4629f0b43a09cd85ec72d7878555172df60f823296873a62faee66729fd440a!]"
    tokentl: "ENCRYPTED[!092501981e947d5da8a498b9c2f0c6b420ebf78cbcdea99b8c9790fa8c5626911549ae7c0abb1799bbe1e75d52511243!]"
    idtl: "ENCRYPTED[!a924f62813282f39f1d2b9aa6062cfd81779d9f6ed1dc7a961b77c222f7006671ad6f2691b6025d40e853f6026e200c0!]"

task:
    name: "Setting Up, Sync, Building and Uploading..."
    timeout_in: 480m
    container:
        image: thisfor/anu:latest
        cpu: 8
        memory: 32G
    gitconfig_file:
        path: /home/cirrus/.gitconfig
        variable_name: gitconfig
    credentials_config_file:
        path: /home/cirrus/.git-credentials
        variable_name: credentials
    rclone_config_file:
        path: /home/cirrus/.rclone.conf
        variable_name: rcloneconfig

    Build-Setup_background_script:
        - curl -s "https://api.telegram.org/bot$tokentl/sendMessage" -d "chat_id=$idtl" -d "text=Build Started! https://cirrus-ci.com/task/$CIRRUS_TASK_ID"
        - mkdir -p ~/rom ~/ccache
        - ./collect.sh -d

    Storage-Checker_background_script:
        - df -h && lsblk && ls -l -a -h
        - ./collect.sh -m

    Sync_script:
        - sleep 10s
        - ./compile.sh -s

    Build_script:
        - ./compile.sh -r

    Upload_script:
        - ./collect.sh -u
