env:
    credentials: "ENCRYPTED[!b81fe387da4d47c382013904c2935d564883e94cd6d6e822a49e2a3068767441b63ca7f7c1747a14e2f1964f96c85b0c!]"
    rcloneconfig: "ENCRYPTED[!6fa09e34ae9fb40e7f080044ac010df0f639d5c229dc1bb823d98645df83a8ba568f1f95cb65eacd9cf9d36fbddcc1da!]"
    tokentl: "ENCRYPTED[!092501981e947d5da8a498b9c2f0c6b420ebf78cbcdea99b8c9790fa8c5626911549ae7c0abb1799bbe1e75d52511243!]"
    idtl: "ENCRYPTED[!a924f62813282f39f1d2b9aa6062cfd81779d9f6ed1dc7a961b77c222f7006671ad6f2691b6025d40e853f6026e200c0!]"
    lunch: lunch lineage_RMX2185-user
    make: mka bacon

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m
  container:
      image: thisfor/make:latest
      cpu: 8
      memory: 32G

  Build-Env-Setup_script:
       - export TZ=Asia/Jakarta && sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
       - 'curl -s "https://api.telegram.org/bot$tokentl/sendMessage" -d "chat_id=$idtl" -d "text=🛠️ Build Started! https://cirrus-ci.com/build/$CIRRUS_BUILD_ID" > /dev/null 2>&1'
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.rclone.conf
       - git config --global user.name rxbi
       - git config --global user.email rxbi@users.noreply.github.com
       - echo "$credentials" > ~/.git-credentials
       - git config --global credential.helper store --file=~/.git-credentials
       - |
         git clone https://github.com/rxbi/rom confx    
         mv confx/configs/*upload* ~/.config
         if [ -f ~/rom/${romfile} ]; then
            echob "anu" > test
            telegram-upload test --to $idtl --caption "$(date)"
         fi

  